### ISSUE TITLE
Dynamic Lighting has no effect on sanity

### ISSUE THREAD

**Issue by someDudeeeee** [ChampionAsh5357/Paranoia#3]
There should be an option for people who use dynamic lighting, weather it be via optifine, the miners hat mod, etc

**Comment by ChampionAsh5357** [comment]
Dynamic lighting is client side and has no effect on the actual gameplay. Mobs can still spawn and your sanity will still drop. You are welcome to try and make a PR for it. However, it's a pointless addition if it does nothing to effect the server side where all the calculations take place.

This is not to mention that the idea is completely overpowered and breaks the concept of the mod.
