### ISSUE TITLE
Sanity sound effects continue to proc after client logs out and returns to main minecraft menu

### ISSUE THREAD

**Issue by Commoble** [ChampionAsh5357/Paranoia#5]
If you leave a server at low sanity, low-sanity sound effects will occasionally occur while idling on the main minecraft menu. If this isn't intended, clearing client-sided player data when the client logs out of a server may prevent this

**Comment by ChampionAsh5357** [comment]
I can’t believe I forgot this as well, thanks

**Comment by ChampionAsh5357** [comment]
Pushed to v1.0.1 Patch 2
